---
title: "lobster_exploration"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
library(here)
```

```{r}
library(janitor)
```

```{r}
lobster_abun <- read_csv(here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", ""))
```

```{r}
lobsters <- lobster_abun |> clean_names() |> uncount(count)
```

```{r}
lob_summary <- lobsters |>
  dplyr::group_by(site, year) |>
  summarise(mean_size_mm = mean(size_mm, na.rm = TRUE),
            sample_size = n())
            
  

```

```{r}
ggplot(data = lob_summary, aes(x = year, y = sample_size)) +
  geom_line(aes(color = site)) +
  labs(title = "Total lobsters observed by year",
       X = "Year",
       Y = "Total lobsters")
```

```{r}
lobster_subset <- lobsters |>
  dplyr::mutate(year = as.numeric(year)) |>
  filter(year == 2020)
 
```

```{r}
lobster_legal <- lobster_subset |>
  dplyr::mutate(legal = case_when(size_mm <= 70 ~ "Yes",
                                  size_mm > 70 ~ "No"))

lobster_legal_new <- lobster_legal |>
  group_by(legal, site) |>
  summarise(n = n())
  

```

```{r}
ggplot(data = lobster_legal_new, aes(x = site, y = n)) +
  geom_col(aes(fill = legal), position = "fill")
```

```{r}
lobsters_subset1 <- lobsters |>
  filter(site %in% c("IVEE", "CARP", "NAPL"))
```

```{r}
lobsters_Aug <- lobsters |>
  filter(month == 8)
```

```{r}
lobsters_subset2 <- lobsters |>
  filter(site == "AQUE" | size_mm > 70)
```

```{r}
lobsters_subset3 <- lobsters |>
  filter(!site == "NAPL")
```

```{r}
lobsters_cal <- lobsters |>
  group_by(site) |>
  summarise(mean = mean(size_mm, na.rm = TRUE),
            standard_dev = sd(size_mm, na.rm = TRUE))

```

```{r}
lobsters_max <- lobsters |>
  group_by(site, month) |>
  summarise(length = max(size_mm, na.rm = TRUE))
```

```{r}
lobsters_new_col <- lobsters |>
  mutate(size_cm = size_mm/10)
```

```{r}
lobsters_lowercase <- lobsters |>
  mutate(site = tolower(site))
```

```{r}
lobsters_area <- lobsters |>
  mutate(area = as.character(area))

#class(lobsters_area$area)
```

```{r}
lobsters_size_bin <- lobsters |>
  mutate(size_bin = case_when(size_mm <= 70 ~"small",
                              size_mm > 70 ~ "large"))
```

```{r}
lobsters_designation <- lobsters |>
  mutate(designation = case_when(site %in% c("IVEE", "NAPL") ~ "MPA", TRUE ~ "not MPA"))
```
